-- NOT EQUAL TOO
SELECT * FROM Employees
WHERE GENDER != 'Female';
-- OR
SELECT * FROM Employees
WHERE GENDER <> 'Female';

-- GREATER THAN
SELECT * FROM Employees
WHERE DATE_OF_BIRTH < '1995-01-01';

-- GREATER THAN OR EQUAL TO
SELECT * FROM Employees
WHERE ID >= 5;

-- LESS THAN
SELECT * FROM Employees
WHERE ID > 10;

-- LESS THAN OR EQUAL TO
SELECT * FROM Employees
WHERE ID <= 20;

-- IS NULL
SELECT * FROM Employees
WHERE DATE_OF_BIRTH IS NULL;

-- IS NOT NULL
SELECT * FROM Employees
WHERE DATE_OF_BIRTH IS NOT NULL;

-- BETWEEN
SELECT * FROM Employees
WHERE DATE_OF_BIRTH BETWEEN
'1990-01-01' AND '2000-12-31';





